apiVersion: 1

# https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources
datasources:
- name: Loki
  type: loki
  access: proxy
  url: $PROVISIONING_DATASOURCES_LOKI_URL
# https://grafana.com/docs/grafana/latest/datasources/tempo/configure-tempo-data-source/
# https://grafana.com/docs/tempo/latest/setup/
# https://github.com/grafana/tempo/tree/main/example/docker-compose
# https://github.com/grafana/tempo/blob/main/example/docker-compose/shared/tempo.yaml
- name: Tempo
  type: tempo
  access: proxy
  basicAuth: false
  url: $PROVISIONING_DATASOURCES_TEMPO_URL
- name: Prometheus
  type: prometheus
  access: proxy
  basicAuth: false
  url: $PROVISIONING_DATASOURCES_PROMETHEUS_URL